DelightFoods_Live/Controllers/SaleOrderController.cs
namespace DelightFoods_Live.Controllers
{
	using DelightFoods_Live.Data;
	using DelightFoods_Live.Models;
	using DelightFoods_Live.Models.DTO;
	using DelightFoods_Live.Utilites;
	using Microsoft.AspNetCore.Http;
	using Microsoft.AspNetCore.Mvc;
	using Microsoft.EntityFrameworkCore;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Security.Claims;
	using System.Threading.Tasks;
	using static TheArtOfDev.HtmlRenderer.Adapters.RGraphicsPath;

	/// <summary>
	/// Defines the <see cref="SaleOrderController" />
	/// </summary>
	public class SaleOrderController : Controller
	{
		/// <summary>
		/// Defines the _context
		/// </summary>
		private readonly ApplicationDbContext _context;

		/// <summary>
		/// Defines the _httpContextAccessor
		/// </summary>
		private readonly IHttpContextAccessor _httpContextAccessor;

		/// <summary>
		/// Initializes a new instance of the <see cref="SaleOrderController"/> class.
		/// </summary>
		/// <param name="context">The context<see cref="ApplicationDbContext"/></param>
		/// <param name="httpContextAccessor">The httpContextAccessor<see cref="IHttpContextAccessor"/></param>
		public SaleOrderController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
		{
			_context = context;
			_httpContextAccessor = httpContextAccessor;
		}

		// GET: SaleOrder

		/// <summary>
		/// The Index
		/// </summary>
		/// <returns>The <see cref="Task{IActionResult}"/></returns>
		public async Task<IActionResult> Index()
		{
			ClaimsPrincipal currentUser = _httpContextAccessor.HttpContext.User;
			string userId = currentUser.FindFirst(ClaimTypes.NameIdentifier)?.Value;
			var customer = _context.Customers.Where(x => x.UserId == userId).FirstOrDefault();

			var returnOrderList = _context.ReturnOrder.Where(x => x.CustomerID == customer.Id).ToList();

			var order = returnOrderList != null && returnOrderList.Any() ?
				 await _context.SaleOrder.Where(x => x.CustomerId == customer.Id && !returnOrderList.Select(x => x.OrderId).Contains(x.Id) && (x.Status != "ReadytoShip" || x.Status != "Returned")).ToListAsync()
				:
				 await _context.SaleOrder.Where(x => x.CustomerId == customer.Id && (x.Status != "ReadytoShip" || x.Status != "Returned")).ToListAsync()
				;
			var orderlist = new List<SaleOrderDTO>();
			var utilities = new MapperClass<SaleOrderModel, SaleOrderDTO>();
			foreach (var item in order)
			{
				var validDate = item.CreatedOnUTC.AddDays(1);
				var shipping = _context.Shipping.Where(x => x.Id == item.ShippingId).FirstOrDefault();
				var payment = _context.PaymentTransaction.Where(x => x.OrderId == item.Id).OrderByDescending(x => x.Id);
				var model = utilities.Map(item);
				model.ShippingAddress = shipping != null ? shipping.Address : "Not Available";
				model.RemainingPayment = item.TotalPrice - payment.Sum(x => x.Amount);
				model.AdvancePayment = payment.Sum(x => x.Amount);
				model.PaymentType = payment != null && payment.Any() ? payment.FirstOrDefault().IsCOD ? "Cash on delivery" : "Card payment" : "Pending";
				model.IsReturnDateIsValde = validDate >= DateTime.Now;
				orderlist.Add(model);
			}

			return View(orderlist);
		}


		public async Task<IActionResult> OrderListForAdmin()
		{
			var order = _context.SaleOrder.OrderBy(x=>x.Status).ToList();
			var orderlist = new List<SaleOrderDTO>();
			var utilities = new MapperClass<SaleOrderModel, SaleOrderDTO>();
			foreach (var item in order)
			{
				var validDate = item.CreatedOnUTC.AddDays(1);
				var shipping = _context.Shipping.Where(x => x.Id == item.ShippingId).FirstOrDefault();
				var payment = _context.PaymentTransaction.Where(x => x.OrderId == item.Id).OrderByDescending(x => x.Id);
				var model = utilities.Map(item);
				model.ShippingAddress = shipping != null ? shipping.Address : "Not Available";
				model.RemainingPayment = item.TotalPrice - payment.Sum(x => x.Amount);
				model.AdvancePayment = payment.Sum(x => x.Amount);
				model.PaymentType = payment != null && payment.Any() ? payment.FirstOrDefault().IsCOD ? "Cash on delivery" : "Card payment" : "Pending";
				model.IsReturnDateIsValde = validDate >= DateTime.Now;
				orderlist.Add(model);
			}
			return View(orderlist);
		}

		// GET: SaleOrder

		/// <summary>
		/// The ReadyForShipOrders
		/// </summary>
		/// <returns>The <see cref="Task{IActionResult}"/></returns>
		public async Task<IActionResult> ReadyForShipOrders()
		{
			ClaimsPrincipal currentUser = _httpContextAccessor.HttpContext.User;
			string userId = currentUser.FindFirst(ClaimTypes.NameIdentifier)?.Value;
			var customer = _context.Customers.Where(x => x.UserId == userId).FirstOrDefault();

			var order = await _context.SaleOrder.Where(x => x.CustomerId == customer.Id && x.Status == "ReadytoShip").ToListAsync();

			var orderlist = new List<SaleOrderDTO>();
			var utilities = new MapperClass<SaleOrderModel, SaleOrderDTO>();
			foreach (var item in order)
			{
				var payment = _context.PaymentTransaction.Where(x => x.OrderId == item.Id).Sum(x => x.Amount);
				var model = utilities.Map(item);
				model.AdvancePayment = payment;
				orderlist.Add(model);
			}

			return View(orderlist);
		}

		// GET: SaleOrder/Details/5

		/// <summary>
		/// The ReadyForShipOrderDetail
		/// </summary>
		/// <param name="id">The id<see cref="int?"/></param>
		/// <returns>The <see cref="Task{IActionResult}"/></returns>
		public async Task<IActionResult> ReadyForShipOrderDetail(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}
			var saleOrderModel = await _context.SaleOrder.FirstOrDefaultAsync(m => m.Id == id);

			if (saleOrderModel == null)
			{
				return NotFound();
			}

			var utilities = new MapperClass<SaleOrderModel, SaleOrderDTO>();
			var model = utilities.Map(saleOrderModel);
			var saleOrderProductMapping = _context.SaleOrderProductMapping.Where(z => z.SaleOrderId == saleOrderModel.Id).ToList();
			var products = saleOrderProductMapping != null && saleOrderProductMapping.Any() ? _context.Product.Where(x => saleOrderProductMapping.Select(z => z.ProductID).Contains(x.Id)).ToList() : null;

			var payment = _context.PaymentTransaction.Where(x => x.OrderId == model.Id).FirstOrDefault();

			foreach (var item in saleOrderProductMapping)
			{
				var product = products != null && products.Any() ? products.Where(x => x.Id == item.ProductID).FirstOrDefault() : null;
				model.AdvancePayment = payment != null ? payment.Amount : 0;
				model.RemainingPayment = payment != null ? model.TotalPrice - payment.Amount : 0;

				model.saleOrderProductMappings.Add(new SaleOrderProductMappingDTO
				{

					ProductID = item.ProductID,
					ProductName = product != null ? product.Name : "",
					Price = item.Price,
					Quantity = item.Quantity,
					Id = item.Id,
					SaleOrderId = item.SaleOrderId
				});
			}

			return View(model);
		}

		// GET: SaleOrder/Details/5

		/// <summary>
		/// The Details
		/// </summary>
		/// <param name="id">The id<see cref="int?"/></param>
		/// <returns>The <see cref="Task{IActionResult}"/></returns>
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}
			var saleOrderModel = await _context.SaleOrder.FirstOrDefaultAsync(m => m.Id == id);

			if (saleOrderModel == null)
			{
				return NotFound();
			}
			var utilities = new MapperClass<SaleOrderModel, SaleOrderDTO>();
			var model = utilities.Map(saleOrderModel);
			var saleOrderProductMapping = _context.SaleOrderProductMapping.Where(z => z.SaleOrderId == saleOrderModel.Id).ToList();
			var products = saleOrderProductMapping != null && saleOrderProductMapping.Any() ? _context.Product.Where(x => saleOrderProductMapping.Select(z => z.ProductID).Contains(x.Id)).ToList() : null;
			model.TotalPrice = saleOrderProductMapping != null && saleOrderProductMapping.Any() ? saleOrderProductMapping.Sum(x => x.Price) : 0;
			model.TaxRate = saleOrderProductMapping != null && saleOrderProductMapping.Any() ? Convert.ToString(saleOrderProductMapping.Sum(x => x.Price) * 0.18M) : "0";
			model.WithHoldingTax = saleOrderProductMapping != null && saleOrderProductMapping.Any() ? Convert.ToString(Convert.ToDecimal(model.TaxRate) + saleOrderProductMapping.Sum(x => x.Price)) : "0";

			var payment = _context.PaymentTransaction.Where(x => x.OrderId == saleOrderModel.Id).OrderByDescending(x => x.Id);

			model.PaymentType = payment != null && payment.Any() ? payment.FirstOrDefault().IsCOD ? "Cash on delivery" : "Card payment" : "Pending";
			foreach (var item in saleOrderProductMapping)
			{
				var product = products != null && products.Any() ? products.Where(x => x.Id == item.ProductID).FirstOrDefault() : null;

				model.saleOrderProductMappings.Add(new SaleOrderProductMappingDTO
				{

					ProductID = item.ProductID,
					ProductName = product != null ? product.Name : "",
					Price = item.Price,
					Quantity = item.Quantity,
					Id = item.Id,
					SaleOrderId = item.SaleOrderId
				});
			}

			return View(model);
		}

		// GET: SaleOrder/Create

		/// <summary>
		/// The Create
		/// </summary>
		/// <returns>The <see cref="IActionResult"/></returns>
		public IActionResult Create()
		{
			return View();
		}

		/// <summary>
		/// The Create
		/// </summary>
		/// <param name="saleOrderModel">The saleOrderModel<see cref="SaleOrderModel"/></param>
		/// <returns>The <see cref="Task{IActionResult}"/></returns>
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(SaleOrderModel saleOrderModel)
		{
			if (ModelState.IsValid)
			{
				_context.Add(saleOrderModel);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(saleOrderModel);
		}

		/// <summary>
		/// The Edit
		/// </summary>
		/// <param name="id">The id<see cref="int?"/></param>
		/// <returns>The <see cref="Task{IActionResult}"/></returns>
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

DelightFoods_Live/Views/SaleOrder/AdminCODOrderList.cshtml
@model IEnumerable<DelightFoods_Live.Models.DTO.SaleOrderDTO>

@{
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
	ViewData["Title"] = "Index";
}

<main id="main" class="main">

	<div class="pagetitle">
		<h1>Sale Order List</h1>
		<nav>
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="/Home/Dashboard">Home</a></li>
				<li class="breadcrumb-item">Sales List</li>
			</ol>
		</nav>
	</div>
	<section class="section">
		<div class="row">
			<p style="float:right">
				@* <a class="btn btn-success" asp-action="Create">Create New</a> *@
			</p>

			<div class="col-lg-12">
				<div class="card">
					<div class="card-body">
						 
						<!-- Table with stripped rows -->
						<div class="datatable-wrapper datatable-loading no-footer sortable searchable fixed-columns">
							<div class="datatable-top">
								@* <div class="datatable-dropdown">
									<label>
										<select class="datatable-selector"><option value="5">5</option><option value="10" selected="">10</option><option value="15">15</option><option value="-1">All</option></select> entries per page
									</label>
								</div> *@
							@* 	<div class="datatable-search">
									<input class="datatable-input" placeholder="Search..." type="search" title="Search within table">
								</div> *@
							</div>
							<div class="datatable-container">
								<table class="table datatable datatable-table">
									<thead>
										<tr>
											<th data-sortable="true" aria-sort="ascending" class="datatable-ascending">
												<button class="datatable-sorter">Code</button>
											</th>
											<th data-sortable="true" aria-sort="ascending" class="datatable-ascending">
												<button class="datatable-sorter">@Html.DisplayNameFor(model => model.CustomerName)</button>
											</th>
											<th data-sortable="true" aria-sort="ascending" class="datatable-ascending">
												<button class="datatable-sorter">@Html.DisplayNameFor(model => model.AdvancePayment)</button>
											</th>
											<th data-sortable="true" aria-sort="ascending" class="datatable-ascending">
												<button class="datatable-sorter">@Html.DisplayNameFor(model => model.TotalPrice)</button>
											</th>
											<th data-sortable="true" aria-sort="ascending" class="datatable-ascending">
												<button class="datatable-sorter">@Html.DisplayNameFor(model => model.Status)</button>
											</th>

											<th data-sortable="true" aria-sort="ascending" class="datatable-ascending">
												<button class="datatable-sorter">
													Created Date
												</button>
											</th>
											<th>Actions</th>
										</tr>
									</thead>
									<tbody>
										@foreach (var item in Model)
										{
											<tr>
												<td>
													<b>@($"COD-ORD-00{item.Id}")</b>
												</td>
												<td>
													@Html.DisplayFor(modelItem => item.CustomerName)
												</td>
												<td>
													@Html.DisplayFor(modelItem => item.AdvancePayment)
												</td>
												<td>
													@Html.DisplayFor(modelItem => item.TotalPrice)
												</td>
												<td>
													@Html.DisplayFor(modelItem => item.Status)
												</td>
												<td>
													@Html.DisplayFor(modelItem => item.CreatedStringDate)
												</td>
												<td>
													@if (item.Status == "WaitingForPaymentConfirmation")
													{
														<button button class="paymentconfirmation btn btn-secondary" data-id="@item.Id">
															Confirm delivery <i class="bi bi-truck"></i>
														</button>

													}

												</td>
											</tr>
										}
									</tbody>
								</table>
							</div>
							@* <div class="datatable-bottom">
								<div class="datatable-info">Showing 1 to 10 of 100 entries</div>
								<nav class="datatable-pagination"><ul class="datatable-pagination-list"><li class="datatable-pagination-list-item datatable-hidden datatable-disabled"><button data-page="1" class="datatable-pagination-list-item-link" aria-label="Page 1">‹</button></li><li class="datatable-pagination-list-item datatable-active"><button data-page="1" class="datatable-pagination-list-item-link" aria-label="Page 1">1</button></li><li class="datatable-pagination-list-item"><button data-page="2" class="datatable-pagination-list-item-link" aria-label="Page 2">2</button></li><li class="datatable-pagination-list-item"><button data-page="3" class="datatable-pagination-list-item-link" aria-label="Page 3">3</button></li><li class="datatable-pagination-list-item"><button data-page="4" class="datatable-pagination-list-item-link" aria-label="Page 4">4</button></li><li class="datatable-pagination-list-item"><button data-page="5" class="datatable-pagination-list-item-link" aria-label="Page 5">5</button></li><li class="datatable-pagination-list-item"><button data-page="6" class="datatable-pagination-list-item-link" aria-label="Page 6">6</button></li><li class="datatable-pagination-list-item"><button data-page="7" class="datatable-pagination-list-item-link" aria-label="Page 7">7</button></li><li class="datatable-pagination-list-item datatable-ellipsis datatable-disabled"><button class="datatable-pagination-list-item-link">…</button></li><li class="datatable-pagination-list-item"><button data-page="10" class="datatable-pagination-list-item-link" aria-label="Page 10">10</button></li><li class="datatable-pagination-list-item"><button data-page="2" class="datatable-pagination-list-item-link" aria-label="Page 2">›</button></li></ul></nav>
							</div> *@
						</div>
						<!-- End Table with stripped rows -->
					</div>
				</div>

			</div>
		</div>
	</section>
</main>

<script>

	$(document).ready(function () {
		$(".paymentconfirmation").click(function () {
			var id = $(this).data("id"); // Get the product ID from data attribute
			console.log('abc', id);

			$.ajax({
				type: 'POST',
				url: "@Url.Action("PaymentConfirm", "SaleOrder")",
				data: { id: id },
				success: function (result) {
					{
						if (result == "success") {
							console.log("Success")
							//alert("Success")
							location.reload();
						}
						else {
							console.log("Error")
							//alert("Error")
						}
					}
				},
				error: function (result) {
				}
			});
		});
	});


</script>

DelightFoods_Live/Views/SaleOrder/AdminOrderList.cshtml
@model IEnumerable<DelightFoods_Live.Models.DTO.SaleOrderDTO>

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewData["Title"] = "Index";
}

<main id="main" class="main">

    <div class="pagetitle">
        <h1>Sale Order List</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/Home/Dashboard">Home</a></li>
                <li class="breadcrumb-item">Sales List</li>
            </ol>
        </nav>
    </div>
    <section class="section">
        <div class="row">
            <p style="float:right">
                @* <a class="btn btn-success" asp-action="Create">Create New</a> *@
            </p>

            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                         
                        <!-- Table with stripped rows -->
                        <div class="datatable-wrapper datatable-loading no-footer sortable searchable fixed-columns">
                           
                            <div class="datatable-container">
                                <table class="table datatable datatable-table">
                                    <thead>
                                        <tr>
                                            <th data-sortable="true" aria-sort="ascending" class="datatable-ascending">
                                                <button class="datatable-sorter">Code</button>
                                            </th>
                                            <th data-sortable="true" aria-sort="ascending" class="datatable-ascending">
                                                <button class="datatable-sorter">@Html.DisplayNameFor(model => model.AdvancePayment)</button>
                                            </th>
                                            <th data-sortable="true" aria-sort="ascending" class="datatable-ascending">
                                                <button class="datatable-sorter">@Html.DisplayNameFor(model => model.TotalPrice)</button>
                                            </th>
                                            <th data-sortable="true" aria-sort="ascending" class="datatable-ascending">
                                                <button class="datatable-sorter">@Html.DisplayNameFor(model => model.Status)</button>
                                            </th>

                                            <th data-sortable="true" aria-sort="ascending" class="datatable-ascending">
                                                <button class="datatable-sorter">
                                                    @Html.DisplayNameFor(model => model.CreatedOnUTC)
                                                </button>
                                            </th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    <b>@($"ORD-00{item.Id}")</b>
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.AdvancePayment)
                                                </td>
                                                
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.TotalPrice)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Status)
                                                </td>

                                                <td>
                                                    @Html.DisplayFor(modelItem => item.CreatedOnUTC)
                                                </td>
                                                <td>
                                                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning">
                                                        Details <i class="bi bi-info-square"></i>
                                                    </a>
                                                    |
                                                    @if (item.Status == "Processing")
                                                    {
                                                        <button button class="readyforship btn btn-secondary" data-id="@item.Id">
                                                            Ready to ship <i class="bi bi-truck"></i>
                                                        </button>

                                                    }

                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                            @* <div class="datatable-bottom">
                                <div class="datatable-info">Showing 1 to 10 of 100 entries</div>
                                <nav class="datatable-pagination"><ul class="datatable-pagination-list"><li class="datatable-pagination-list-item datatable-hidden datatable-disabled"><button data-page="1" class="datatable-pagination-list-item-link" aria-label="Page 1">‹</button></li><li class="datatable-pagination-list-item datatable-active"><button data-page="1" class="datatable-pagination-list-item-link" aria-label="Page 1">1</button></li><li class="datatable-pagination-list-item"><button data-page="2" class="datatable-pagination-list-item-link" aria-label="Page 2">2</button></li><li class="datatable-pagination-list-item"><button data-page="3" class="datatable-pagination-list-item-link" aria-label="Page 3">3</button></li><li class="datatable-pagination-list-item"><button data-page="4" class="datatable-pagination-list-item-link" aria-label="Page 4">4</button></li><li class="datatable-pagination-list-item"><button data-page="5" class="datatable-pagination-list-item-link" aria-label="Page 5">5</button></li><li class="datatable-pagination-list-item"><button data-page="6" class="datatable-pagination-list-item-link" aria-label="Page 6">6</button></li><li class="datatable-pagination-list-item"><button data-page="7" class="datatable-pagination-list-item-link" aria-label="Page 7">7</button></li><li class="datatable-pagination-list-item datatable-ellipsis datatable-disabled"><button class="datatable-pagination-list-item-link">…</button></li><li class="datatable-pagination-list-item"><button data-page="10" class="datatable-pagination-list-item-link" aria-label="Page 10">10</button></li><li class="datatable-pagination-list-item"><button data-page="2" class="datatable-pagination-list-item-link" aria-label="Page 2">›</button></li></ul></nav>
                            </div> *@
                        </div>
                        <!-- End Table with stripped rows -->
                    </div>
                </div>

            </div>
        </div>
    </section>
</main>

<script>

    $(document).ready(function () {
        $(".readyforship").click(function () {
            var id = $(this).data("id"); // Get the product ID from data attribute
            console.log('abc', id);

            $.ajax({
                type: 'POST',
                url: "@Url.Action("ReadyToShip", "SaleOrder")",
                data: { id: id },
                success: function (result) {
                    {
                        if (result == "success") {
                            // alert("Success")
                            console.log("Success")
                            location.reload();
                        }
                        else {
                            // alert("Error")
                            console.log("Error")
                        }
                    }
                },
                error: function (result) {
                }
            });
        });
    });


</script>

DelightFoods_Live/Views/SaleOrder/AdminReturnOrderList.cshtml
@model IEnumerable<DelightFoods_Live.Models.DTO.SaleOrderDTO>

@{
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
	ViewData["Title"] = "Index";
}

<h1>Index</h1>


<main id="main" class="main">

	<div class="pagetitle">
		<h1>Return Order List</h1>
		<nav>
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="/Home/Dashboard">Home</a></li>
				<li class="breadcrumb-item">Sales List</li>
			</ol>
		</nav>
	</div>

	<section class="section">
		<div class="row">
			<p style="float:right">
				@* <a class="btn btn-success" asp-action="Create">Create New</a> *@
			</p>

	<table class="table">
		<thead>
			<tr>
				<th>
					Code
				</th>
				<th>
					Product Name
				</th>
				<th>
					@Html.DisplayNameFor(model => model.CustomerName)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.TotalPrice)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Status)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Reason)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.ReturnDate)
				</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model)
			{
				<tr>
					<td>
						<b>@($"R-ORD-REQ-00{item.Id}")</b>
					</td>
					<td>
						Discada (Plow Disc BBQ)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.CustomerName)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.TotalPrice)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Status)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Reason)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.ReturnDate)
					</td>
					<td>
						@if (item.Status != "Returned")
						{
							<button button class="returnConfirmbtn btn btn-secondary" data-id="@item.Id">Return Confirm</button>
						}
					</td>
				</tr>
			}
		</tbody>
	</table>
		</div>

	</section>

</main>



<script>

	$(document).ready(function () {
		$(".returnConfirmbtn").click(function () {
			var id = $(this).data("id");
			$.ajax({
				type: "POST",
				url: "@Url.Action("ReturnApprove", "SaleOrder")",
				data: { id: id },
				success: function (result) {
					{
						if (result == "success") {
							// alert("Success")
							console.log("Success")
							location.reload();
						}
						else {
							// alert("Error")
							console.log("Error")
						}
					}
				},
				error: function (result) {
				}
			});
		});
	});
</script>

DelightFoods_Live/Views/SaleOrder/Create.cshtml
@model DelightFoods_Live.Models.SaleOrderModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SaleOrderModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <input asp-for="CustomerId" class="form-control" />
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippingId" class="control-label"></label>
                <input asp-for="ShippingId" class="form-control" />
                <span asp-validation-for="ShippingId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedOnUTC" class="control-label"></label>
                <input asp-for="CreatedOnUTC" class="form-control" />
                <span asp-validation-for="CreatedOnUTC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}